"use client";
import React, { useState } from 'react';

export default function PlatformIntegrationPage({ params }) {
  // React unwraps the dynamic URL parameter (e.g., 'woocommerce')
  const platformName = params.platform.charAt(0).toUpperCase() + params.platform.slice(1);
  const [responseMsg, setResponseMsg] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  // This function fires to your AWS API Gateway when the button is clicked
  const testAwsConnection = async () => {
    setIsLoading(true);
    setResponseMsg("");

    try {
      const res = await fetch("https://d8v01rrw7d.execute-api.af-south-1.amazonaws.com/Prod/invoice/clear", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          platform: params.platform,
          order_id: `TEST-${Math.floor(Math.random() * 10000)}` 
        })
      });

      const data = await res.json();
      // Displays the success message generated by your Lambda function
      setResponseMsg(data.message || "Connection successful.");
    } catch (error) {
      setResponseMsg("Network error connecting to AWS.");
    }
    
    setIsLoading(false);
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center py-20">
      <div className="max-w-3xl px-6 w-full">
        <h1 className="text-4xl font-extrabold text-gray-900 mb-4 tracking-tight">
          Automate Peppol E-Invoicing for {platformName}
        </h1>
        <p className="text-xl text-gray-600 mb-10">
          Don't build complex XML routing from scratch. Send standard JSON from your {platformName} server, and our API handles the UBL 2.1 mapping and Peppol network routing.
        </p>

        <div className="bg-gray-900 rounded-lg p-6 mb-8 shadow-xl">
          <div className="text-xs text-gray-400 mb-2 uppercase tracking-wide">POST /invoice/clear</div>
          <pre className="text-green-400 font-mono text-sm overflow-x-auto">
            {`curl -X POST "https://api.octothorp.online/invoice/clear" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "platform": "${params.platform}",
    "order_id": "INV-1234"
  }'`}
          </pre>
        </div>

        <div className="flex flex-col sm:flex-row gap-4 items-center">
          <button 
            onClick={testAwsConnection}
            disabled={isLoading}
            className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-8 rounded-md transition-colors w-full sm:w-auto disabled:opacity-50"
          >
            {isLoading ? "Pinging Cape Town..." : "Test AWS Lambda Connection"}
          </button>
          
          {responseMsg && (
            <span className="text-sm font-mono text-green-700 bg-green-100 px-3 py-2 rounded-md">
              {responseMsg}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}